
import React, { useState } from 'react';
import type { IrisAnalysis } from '../types';
import AnalysisCard from './AnalysisCard';
import RarityMeter from './RarityMeter';
import { 
    IconDna, IconShield, IconFingerprint, IconGlobe, IconSparkles, IconEye, 
    IconArrowLeft, IconShare, IconSave, IconPatternTag, IconBarChart, 
    IconMapPin, IconGeneticProbability 
} from './IconComponents';
import PatternInfoModal from './PatternInfoModal';

interface AnalysisResultProps {
  result: IrisAnalysis;
  imageSrc: string;
  onReset: () => void;
}

const AnalysisResult: React.FC<AnalysisResultProps> = ({ result, imageSrc, onReset }) => {
  const [selectedPattern, setSelectedPattern] = useState<{ name: string; description: string; } | null>(null);
  const { ancestry, ...restOfResult } = result;

  const cardData = [
    { icon: <IconShield className="w-8 h-8" />, data: restOfResult.healthClues },
    { icon: <IconFingerprint className="w-8 h-8" />, data: restOfResult.biometricSignature },
    { icon: <IconSparkles className="w-8 h-8" />, data: restOfResult.personalityVibe },
    { icon: <IconEye className="w-8 h-8" />, data: restOfResult.pigmentOddities },
  ];

  const handleSave = () => {
    let reportContent = `Iris Analyzer Analysis
================================
Date: ${new Date().toLocaleString()}`;

    // 1. Unique Patterns
    if (result.uniquePatterns && result.uniquePatterns.length > 0) {
      reportContent += `

--- Unique Patterns Detected ---
${result.uniquePatterns.map(p => `\n* ${p.name}\n  ${p.description}`).join('')}
`;
    }

    // 2. Metrics
    reportContent += `

--- Metrics ---
Rarity Score: ${100 - result.rarityIndex.percentage}/100
Ancestry - Global Prevalence: ${result.ancestry.metrics.globalPrevalence}
Ancestry - Regional Hotspots: ${result.ancestry.metrics.regionalHotspots.join(', ')}
Ancestry - Genetic Probability: ${result.ancestry.metrics.geneticProbability}
`;

    // 3. All findings/insights
    reportContent += `

--- All Findings & Insights ---

[${result.dominantColor.name} - Color Profile]
Confidence: ${result.dominantColor.confidence}%
Hex Code: ${result.dominantColor.hexCode}
Color Composition:
${result.colorComposition.map(c => `  - ${c.colorName} (${c.hexCode}): ${c.percentage}%`).join('\n')}

[${result.rarityIndex.title}]
${result.rarityIndex.description}

[${result.ancestry.title}]
${result.ancestry.description}

[${result.healthClues.title}]
${result.healthClues.description}

[${result.biometricSignature.title}]
${result.biometricSignature.description}

[${result.personalityVibe.title}]
${result.personalityVibe.description}

[${result.pigmentOddities.title}]
${result.pigmentOddities.description}
`;
    
    // 4. Footer
    reportContent += `

================================
Generated by Iris Analyzer. For entertainment purposes only.
`;
    
    const blob = new Blob([reportContent.trim()], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `iris-analysis-${Date.now()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const dataURItoBlob = (dataURI: string) => {
    const byteString = atob(dataURI.split(',')[1]);
    const mimeString = dataURI.split(',')[0].split(':')[1].split(';')[0];
    const ab = new ArrayBuffer(byteString.length);
    const ia = new Uint8Array(ab);
    for (let i = 0; i < byteString.length; i++) {
        ia[i] = byteString.charCodeAt(i);
    }
    return new Blob([ab], { type: mimeString });
  }

  const handleShare = async () => {
    const analysisText = `Check out my iris analysis from Iris Analyzer!
- Rarity: ${100 - result.rarityIndex.percentage}% Rare (${result.rarityIndex.title})
- Personality Vibe: ${result.personalityVibe.title}
- Ancestry Guess: ${result.ancestry.title}`;
    
    try {
        if (!navigator.share) {
            alert('Share API is not supported in your browser.');
            return;
        }

        const blob = dataURItoBlob(imageSrc);
        const file = new File([blob], "iris-analyzer.jpg", { type: "image/jpeg", lastModified: Date.now() });
        const shareData: ShareData = {
            title: 'My Iris Analyzer Analysis',
            text: analysisText,
        };

        if (navigator.canShare && navigator.canShare({ files: [file] })) {
            shareData.files = [file];
        }

        await navigator.share(shareData);

    } catch (error) {
        console.error('Error sharing analysis:', error);
    }
  };


  return (
    <div className="animate-slide-in-up w-full">
      <header className="text-center mb-8">
        <h1 className="text-4xl md:text-5xl font-extrabold text-white">Your Iris Analysis</h1>
        <p className="mt-2 text-lg text-gray-300">Here's what our AI discovered in your eye.</p>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left Column: Image and Rarity */}
        <div className="lg:col-span-1 flex flex-col gap-6">
          <div className="bg-white/10 p-5 rounded-xl border border-white/20 flex flex-col items-center justify-center">
            <img 
              src={imageSrc} 
              alt="Analyzed eye" 
              className="w-48 h-48 rounded-full object-cover border-4 border-brand-teal shadow-lg"
            />
            <p className="mt-4 text-gray-400 text-sm">Your unique iris</p>
          </div>
          
          {result.uniquePatterns && result.uniquePatterns.length > 0 && (
            <div className="bg-white/10 p-5 rounded-xl border border-white/20">
              <div className="flex items-center gap-3 mb-4">
                <IconFingerprint className="w-6 h-6 text-white/80" />
                <h3 className="text-xl font-bold text-white">Unique Patterns Detected</h3>
              </div>
              <div className="flex flex-wrap items-center gap-2">
                {result.uniquePatterns.map((pattern, index) => (
                  <button
                    key={index}
                    onClick={() => setSelectedPattern(pattern)}
                    className="bg-brand-purple/80 hover:bg-brand-purple text-white font-semibold py-1.5 px-3 rounded-full text-sm inline-flex items-center gap-2 transition-all transform hover:scale-105"
                  >
                    <IconPatternTag className="w-4 h-4"/>
                    {pattern.name}
                  </button>
                ))}
                <span className="text-white text-xs ml-2 animate-pulse">click here</span>
              </div>
            </div>
          )}

          <RarityMeter 
            icon={<IconGlobe className="w-8 h-8"/>} 
            title={result.rarityIndex.title}
            description={result.rarityIndex.description}
            percentage={result.rarityIndex.percentage}
          />
        </div>

        {/* Right Column: Analysis Cards */}
        <div className="lg:col-span-2 grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="bg-white/10 backdrop-blur-sm p-5 rounded-xl border border-white/20 flex flex-col">
                <div className="flex items-center gap-4">
                    <div className="text-brand-teal"><IconDna className="w-8 h-8" /></div>
                    <h3 className="text-xl font-bold text-white">{ancestry.title}</h3>
                </div>
                <p className="text-gray-300 mt-3 text-base">{ancestry.description}</p>
                {ancestry.metrics && (
                    <div className="mt-4 pt-4 border-t border-white/10">
                        <h4 className="flex items-center gap-2 text-sm font-bold text-white mb-3">
                            <IconBarChart className="w-5 h-5" />
                            Metrics
                        </h4>
                        <ul className="space-y-2 text-sm">
                            <li className="flex justify-between items-center">
                                <span className="flex items-center gap-2 text-gray-300"><IconGlobe className="w-4 h-4" /> Global Prevalence:</span>
                                <span className="font-bold text-white">{ancestry.metrics.globalPrevalence}</span>
                            </li>
                            <li className="flex justify-between items-center">
                                <span className="flex items-center gap-2 text-gray-300"><IconMapPin className="w-4 h-4" /> Regional Hotspots:</span>
                                <span className="font-bold text-white">{ancestry.metrics.regionalHotspots.join(', ')}</span>
                            </li>
                            <li className="flex justify-between items-center">
                                <span className="flex items-center gap-2 text-gray-300"><IconGeneticProbability className="w-4 h-4" /> Genetic Probability:</span>
                                <span className="font-bold text-white">{ancestry.metrics.geneticProbability}</span>
                            </li>
                        </ul>
                    </div>
                )}
            </div>
          {cardData.map((item, index) => (
            <AnalysisCard key={index} icon={item.icon} title={item.data.title} description={item.data.description} />
          ))}
        </div>
      </div>
      
      <div className="text-center mt-10">
        <div className="flex flex-col sm:flex-row justify-center items-center gap-4">
            <button
              onClick={handleShare}
              className="bg-brand-purple hover:bg-purple-700 text-white font-bold py-3 px-6 rounded-lg transition-all duration-300 transform hover:scale-105 shadow-lg inline-flex items-center justify-center gap-2 w-full sm:w-auto"
              aria-label="Share analysis"
            >
              <IconShare className="w-5 h-5" />
              <span>Share</span>
            </button>
            <button
              onClick={handleSave}
              className="bg-brand-purple hover:bg-purple-700 text-white font-bold py-3 px-6 rounded-lg transition-all duration-300 transform hover:scale-105 shadow-lg inline-flex items-center justify-center gap-2 w-full sm:w-auto"
              aria-label="Save analysis text"
            >
              <IconSave className="w-5 h-5" />
              <span>Save</span>
            </button>
            <button
              onClick={onReset}
              className="bg-brand-purple hover:bg-purple-700 text-white font-bold py-3 px-6 rounded-lg transition-all duration-300 transform hover:scale-105 shadow-lg inline-flex items-center justify-center gap-2 w-full sm:w-auto"
              aria-label="Analyze another image"
            >
              <IconArrowLeft className="w-5 h-5" />
              <span>Analyze Another</span>
            </button>
        </div>
      </div>

      {selectedPattern && (
        <PatternInfoModal 
          pattern={selectedPattern}
          onClose={() => setSelectedPattern(null)}
        />
      )}
    </div>
  );
};

export default AnalysisResult;
